from tkinter import *
from PIL import ImageTk,Image
import random
root=Tk()
root.title("pokemon card game")
root.geometry("600x400")
root.configure(background="orange")
pikachu=ImageTk.PhotoImage(Image.open("pikachu.png"))
charmander=ImageTk.PhotoImage(Image.open("charmander.png"))
charizard=ImageTk.PhotoImage(Image.open("charizard.png"))
abra=ImageTk.PhotoImage(Image.open("abra.png"))
kadabra=ImageTk.PhotoImage(Image.open("Kadabra.png"))
meowth=ImageTk.PhotoImage(Image.open("meowth.jpg"))
squirtle=ImageTk.PhotoImage(Image.open("squirtle.png"))
persian=ImageTk.PhotoImage(Image.open("persian.png"))
jigglypuff=ImageTk.PhotoImage(Image.open("jigglypuff.jpg"))
nidoking=ImageTk.PhotoImage(Image.open("nidoking.png"))
ivysaur=ImageTk.PhotoImage(Image.open("ivysaur.png"))
bulbasaur=ImageTk.PhotoImage(Image.open("bulbasaur.png"))
label_player1=Label(root,text="player1",bg="red",fg="white")
label_player2=Label(root,text="player2",bg="green",fg="black")
label_player1.place(relx=0.1,rely=0.3,anchor=CENTER)
label_player2.place(relx=0.9,rely=0.3,anchor=CENTER)
label_score1=Label(root,bg="royal blue",fg="white")
label_score2=Label(root,bg="royal blue",fg="white")
label_score1.place(relx=0.1,rely=0.4,anchor=CENTER)
label_score2.place(relx=0.9,rely=0.4,anchor=CENTER)
label_rand_no=Label(root)
label_rand_no.place(relx=0.5,rely=0.5,anchor=CENTER)
root.mainloop()